model_list:
  - model_name: claude-3.7
    litellm_params:
      model: claude-3-7-sonnet-20250219
      api_key: "os.environ/ANTHROPIC_API_KEY"
  - model_name: claude-sonnet-4-5
    litellm_params:
      model: claude-sonnet-4-5-20250929
      api_key: "os.environ/ANTHROPIC_API_KEY"